[package]
name="rom-mysql"
version.workspace=true
edition.workspace=true
rust-version.workspace=true
license.workspace=true
repository.workspace=true
publish.workspace=true
[dependencies]
rom-sql-core={path="../rom-sql-core",version="=0.1.0-dev"}
mysql_async={version="=0.37.1",default-features=false,features=["minimal-rust","native-tls-tls"]}
tokio={version="=1.53.1",features=["rt","net","time"]}
[lints]
workspace=true
