[package]
name = "smtp-public-consumer"
version = "0.0.0"
edition = "2024"

[workspace]

[dependencies]
rom = { git = "https://github.com/pmikstacki/ROM", rev = "d7ef529040eec60dc869034c2d33130219db85fe", default-features = false, features = ["derive"] }
rom-email-core = { path = "../../crates/rom-email-core" }
rom-smtp = { path = "../../crates/rom-smtp" }
tokio = { version = "=1.53.1", features = ["rt", "macros"] }
rom-sqlite = { git = "https://github.com/pmikstacki/ROM", rev = "d7ef529040eec60dc869034c2d33130219db85fe" }
rom-redb = { git = "https://github.com/pmikstacki/ROM", rev = "d7ef529040eec60dc869034c2d33130219db85fe" }
