[package]
name = "rom-oracle"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
[dependencies]
rom-sql-core = { version = "0.1.0-dev", path = "../rom-sql-core" }
oracle = "=0.6.3"
tokio = { version = "=1.53.1", features = ["rt"] }
[lints]
workspace = true
